import type { Metadata } from 'next'
import { JetBrains_Mono, Nunito_Sans, Work_Sans } from 'next/font/google'

export const metadata: Metadata = {
  title: 'Hua Sheng Tan',
  description: 'Personal Website: Generated by Github page',
}

const jetBrain = JetBrains_Mono({
  subsets: ['latin'],
  variable: '--jetBrain',
})

const nunitoSans = Nunito_Sans({
  subsets: ['latin'],
  variable: '--nunitoSans',
})

const workSans = Work_Sans({
  subsets: ['latin'],
  variable: '--workSans',
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body
        className={`antialiased ${jetBrain.variable} ${nunitoSans.variable} ${workSans.variable}`}
      >
        {children}
      </body>
    </html>
  )
}
